### ISSUE TITLE
EMQ_CLUSTER__K8S__APISERVER should not quoted in k8s 1.7.1

### ISSUE THREAD

**Issue by jngbng** [felipejfc/emqtt-k8s#1]
I tried your script and found that auto clustering won't work.
After unquoting EMQ_CLUSTER__K8S__APISERVER value to "https://kubernetes.default:443", it worked well.

**Comment by villadalmine** [comment]
It did not work for me with or without, error log send me problem with discovery api, someone test in in gke ?

**Comment by villadalmine** [comment]
/opt/emqttd # cat log/error.log                                                                                                                                             
2018-04-25 15:14:32.347 [error] <0.1259.0>@ekka_autocluster:discover_and_join:84 Ekka(AutoCluster): Discovery error: {403,"{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"endpoints \\\"emqtt\\\" is forbidden: User \\\"system:serviceaccount:emqtt:default\\\" cannot get endpoints in the namespace \\\"emqtt\\\": Unknown user \\\"system:serviceaccount:emqtt:default\\\"\",\"reason\":\"Forbidden\",\"details\":{\"name\":\"emqtt\",\"kind\":\"endpoints\"},\"code\":403}\n"}  
/opt/emqttd #

**Comment by felipejfc** [comment]
@villadalmine it seems a problem with RBAC you have to grant privileges on namespace emqtt to the service account emqtt is using, in this case it seems to be "system:serviceaccount:emqtt:default"

**Comment by villadalmine** [comment]
I never touch anything in GKE, im using as default configuration, I will try without using emqtt namespace or trying RBAC. Also im using a load balancer, at least works for one node and then I can add other nodes  with command line, but I do not know if the balancer will work after of that I think I need to tune more the configuration of cluster to get more logs. I want to use it as a production cluster for mqtt broker, just doing testing. Thanks !!

**Comment by villadalmine** [comment]
It did not work, i tested with default namespaces.
apiVersion: v1
kind: Service
metadata:
  name: emqtt
  labels:
    app: emqtt
spec:
  ports:
    - port: 1883
      name: mqtt
    - port: 8883
      name: mqttssl
    - port: 8080
      name: mgmt
    - port: 18083
      name: dashboard
    - port: 4369
      name: mapping
  clusterIP: None
  selector:
    app: emqtt
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: emqtt
  #namespace: emqtt
spec:
  replicas: 2
  serviceName: emqtt
  template:
    metadata:
      labels:
        app: emqtt
    spec:
  #    subdomain: default-subdomain
      containers:
      - name: emqtt
        image: felipejfc/emqtt:v1
        ports:
          - containerPort: 1883
          - containerPort: 8883
          - containerPort: 8080
          - containerPort: 18083
          - containerPort: 4369
          - containerPort: 4370
          - containerPort: 6369
          - containerPort: 6370
          - containerPort: 6371
          - containerPort: 6372
          - containerPort: 6373
          - containerPort: 6374
          - containerPort: 6375
          - containerPort: 6376
          - containerPort: 6377
          - containerPort: 6378
        readinessProbe:
          tcpSocket:
            port: 1883
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
          - name: EMQ_NAME
            value: "emqtt"
  #        - name: EMQ_JOIN_CLUSTER
#            value: "emqcl"
    #      - name: GET_HOSTS_FROM
    #        value: dns
          - name: EMQ_CLUSTER__DISCOVERY
            value: "k8s"
          - name: EMQ_CLUSTER__K8S__APISERVER
          #  value: "https://kubernetes.default:443"
            #value: 'https://kubernetes.default:443'
            value: "https:\\/\\/kubernetes.default.svc.cluster.local:443"
          - name: EMQ_CLUSTER__K8S__SERVICE_NAME
            value: "emqtt"
          - name: EMQ_CLUSTER__K8S__ADDRESS_TYPE
            value: "ip"
          - name: EMQ_CLUSTER__K8S__APP_NAME
            value: "emqtt"
          - name: EMQ_NODE__COOKIE
            value: "secretcookieeeetfggggg"
          - name: EMQ_CLUSTER__NAME
            value: "emqtt"
          - name: EMQ_CLUSTER__AUTOHEAL
            value: "on"
          - name: EMQ_CLUSTER__AUTOCLEAN
            value: "5m"


/opt/emqttd # bin/emqttd_ctl cluster status
Cluster status: [{running_nodes,['emqtt@10.8.2.27']}]                                 
/opt/emqttd # cat log/
crash.log  error.log 
/opt/emqttd # cat log/error.log 
2018-04-26 11:22:12.263 [error] <0.1259.0>@ekka_autocluster:discover_and_join:84 Ekka(AutoCluster): Discovery error: {403,"{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"endpoints \\\"emqtt\\\" is forbidden: User \\\"system:serviceaccount:default:default\\\" cannot get endpoints in the namespace \\\"default\\\": Unknown user \\\"system:serviceaccount:default:default\\\"\",\"reason\":\"Forbidden\",\"details\":{\"name\":\"emqtt\",\"kind\":\"endpoints\"},\"code\":403}\n"}
/opt/emqttd # ping kubernetes.default.svc.cluster.local                               
PING kubernetes.default.svc.cluster.local (10.11.240.1): 56 data bytes                
^C                   
--- kubernetes.default.svc.cluster.local ping statistics ---                          
3 packets transmitted, 0 packets received, 100% packet loss                           
/opt/emqttd # ping kubernetes.default      
PING kubernetes.default (10.11.240.1): 56 data bytes                                  
^C                   
--- kubernetes.default ping statistics --- 
3 packets transmitted, 0 packets received, 100% packet loss                           
/opt/emqttd #


/opt/emqttd # cat /etc/hosts                                                                                   
# Kubernetes-managed hosts file.                                                                               
127.0.0.1       localhost                                                                                      
::1     localhost ip6-localhost ip6-loopback                                                                   
fe00::0 ip6-localnet                                                                                           
fe00::0 ip6-mcastprefix                                                                                        
fe00::1 ip6-allnodes                                                                                           
fe00::2 ip6-allrouters                                                                                         
10.8.2.27       emqtt-0.emqtt.default.svc.cluster.local emqtt-0                                                
10.8.2.27        10.8.2.27                                                                                     
/opt/emqttd # cat /etc/resolv.conf                                                                             
nameserver 10.11.240.10                                                                                        
search default.svc.cluster.local svc.cluster.local cluster.local c.alliot-198712.internal google.internal      
options ndots:5                                                                                                
/opt/emqttd # 

/opt/emqttd # ping emqtt-1                                                                                     
ping: bad address 'emqtt-1'                                                                                    
/opt/emqttd # nslookup emqtt-1                                                                                 
nslookup: can't resolve '(null)': Name does not resolve                                                        
                                                                                                               
nslookup: can't resolve 'emqtt-1': Name does not resolve                                                       
/opt/emqttd # 

Any idea ?

I do not know if the k8s dns discovery is the correct.

**Comment by villadalmine** [comment]
/opt/emqttd # bin/emqttd_ctl cluster status                                                                                                                                                                       
Cluster status: [{running_nodes,['emqtt@10.8.2.31','emqtt@10.8.1.27']}]                                                                                                                                           
/opt/emqttd # 
but i set permissive RBAC, so i need to read more carefully about RBAC, thanks

**Comment by villadalmine** [comment]
@felipejfc  I have this yaml, now it is working with RBAC, but i really want to check to only add the correct role to use discovery stuff. But now is working and can scale and downgrade.
``` apiVersion: v1
kind: Namespace
metadata:
  name: emqtt
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: emqtt-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - "namespaces"
      - "pods"
    verbs:
      - "list"
      - "get"
      - "watch"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: eqmtt-clusterrole
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eqmtt-clusterrole
subjects:
- kind: ServiceAccount
  name: eqmtt
  namespace: eqmtt
---
apiVersion: v1
kind: Service
metadata:
  name: emqtt
  namespace: emqtt
  labels:
    app: emqtt
spec:
  type: LoadBalancer
  ports:
    - port: 1883
      nodePort: 30001
      protocol: TCP
      name: mqtt
    - port: 8883
      nodePort: 30002
      protocol: TCP
      name: mqttssl
    - port: 8080
      nodePort: 30003
      protocol: TCP
      name: mgmt
    - port: 18083
      nodePort: 30004
      protocol: TCP
      name: dashboard
    - port: 4369
      nodePort: 30005
      protocol: TCP
      name: mapping
  selector:
    app: emqtt
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: emqtt
  namespace: emqtt
spec:
  replicas: 2
  serviceName: emqtt
  template:
    metadata:
      labels:
        app: emqtt
    spec:
      containers:
      - name: emqtt
        image: felipejfc/emqtt:v1
        ports:
          - containerPort: 1883
          - containerPort: 8883
          - containerPort: 8080
          - containerPort: 18083
          - containerPort: 4369
          - containerPort: 4370
          - containerPort: 6369
          - containerPort: 6370
          - containerPort: 6371
          - containerPort: 6372
          - containerPort: 6373
          - containerPort: 6374
          - containerPort: 6375
          - containerPort: 6376
          - containerPort: 6377
          - containerPort: 6378
        readinessProbe:
          tcpSocket:
            port: 1883
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
          - name: EMQ_NAME
            value: "emqtt"
          - name: EMQ_CLUSTER__DISCOVERY
            value: "k8s"
          - name: EMQ_CLUSTER__K8S__APISERVER
            value: "https:\\/\\/kubernetes.default.svc.cluster.local:443"
          - name: EMQ_CLUSTER__K8S__SERVICE_NAME
            value: "emqtt"
          - name: EMQ_CLUSTER__K8S__ADDRESS_TYPE
            value: "ip"
          - name: EMQ_CLUSTER__K8S__APP_NAME
            value: "emqtt"
          - name: EMQ_NODE__COOKIE
            value: "secretcookieeeetfggggg"
          - name: EMQ_CLUSTER__NAME
            value: "emqtt"
          - name: EMQ_CLUSTER__AUTOHEAL
            value: "on"
          - name: EMQ_CLUSTER__AUTOCLEAN
            value: "5m"
```

**Comment by felipejfc** [comment]
@villadalmine glad to hear it's working now :D

closing this issue
