### ISSUE TITLE
Ports 6369 to 6378?

### ISSUE THREAD

**Issue by p-mendes** [felipejfc/emqtt-k8s#3]
Hi Felipe, first of all a big thank you for this example! This is more a question than an issue: why do you expose ports 6369 to 6378? I have removed them from the SatefulSet and it doesn't seem to make a difference. Also cannot find reference to these ports anywhere on EMQ's docs.

**Comment by lcofre** [comment]
When there's more than one emqx server forming a cluster, those ports are used for the nodes to communicate. https://github.com/emqx/emqx/issues/1576#issuecomment-383814852

**Comment by felipejfc** [comment]
that's exactly as @lcofre said, anyway, removing them from the statefulset should not affect the habillity of containers talking among them inside the kube cluster

I guess your question is answered, so I'm closing this issue, feel free to reopen it if you need...

best!
